name: "OpenAPI Generator Action"
description: "Run the OpenAPI Generator CLI in a Github Action."
branding:
  icon: activity
  color: blue
runs:
  using: "docker"
  image: "docker://openapitools/openapi-generator-cli"
